---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Name }}
data:
{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-indices-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Name }}
data:
{{ (.Files.Glob "indices/*").AsConfig | indent 2 }}